(()=>{'use strict';
const messages=window.LEMON_MESSAGES,config=window.LEMON_CONFIG||{},$=id=>document.getElementById(id);let mood='all',current=messages.find(m=>m.id==='sarcastic-7');
const labels={funny:'A LITTLE LAUGH',sarcastic:'EXTRA SHARP',kind:'A LITTLE KINDNESS',useful:'ONE USEFUL NUDGE'};
function track(name,data={}){window.dispatchEvent(new CustomEvent('lemon:event',{detail:{name,...data}}));if(typeof window.plausible==='function')window.plausible(name,{props:data});}
function show(item,daily=false){current=item;$('message').textContent=item.text;$('label').textContent=daily?'TODAY’S LEMON':labels[item.category];const u=new URL(location.href);u.searchParams.set('lemon',item.id);try{history.replaceState(null,'',u)}catch{}$('status').textContent='';}
function squeeze(){const pool=messages.filter(m=>(mood==='all'||m.category===mood)&&m.id!==current.id);show(pool[Math.floor(Math.random()*pool.length)]);const el=$('squeeze');el.classList.remove('squeezed');void el.offsetWidth;el.classList.add('squeezed');track('squeeze',{category:current.category});}
$('squeeze').onclick=squeeze;$('another').onclick=squeeze;
document.querySelectorAll('[data-mood]').forEach(b=>b.onclick=()=>{mood=b.dataset.mood;document.querySelectorAll('[data-mood]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));squeeze();});
$('daily').onclick=()=>{const date=new Date().toISOString().slice(0,10);let hash=0;for(const c of date)hash=(hash*31+c.charCodeAt(0))>>>0;show(messages[hash%messages.length],true);track('daily');};
const requested=new URLSearchParams(location.search).get('lemon');if(requested){const found=messages.find(m=>m.id===requested);if(found)show(found);}
function url(){return 'https://iflifegivesyoulemons.com/?lemon='+encodeURIComponent(current.id);}
$('share').onclick=async()=>{const data={title:'A little lemon for you',text:current.text,url:url()};try{if(navigator.share){await navigator.share(data);track('share',{method:'native'});$('status').textContent='A little zest passed on.';}else{await navigator.clipboard.writeText(data.text+'\n'+data.url);track('share',{method:'copy'});$('status').textContent='Message and link copied. Paste them into your favourite app.';}}catch(e){if(e.name!=='AbortError'){$('status').textContent='Copy this link to share: '+url();}}};
function imageBlob(){return new Promise((resolve,reject)=>{const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1080;const ctx=canvas.getContext('2d');ctx.fillStyle='#faf8ef';ctx.fillRect(0,0,1080,1080);ctx.fillStyle='#f8d848';ctx.beginPath();ctx.ellipse(900,120,150,115,-.4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#3f593d';ctx.font='bold 24px Arial';ctx.fillText('IF LIFE GIVES YOU LEMONS',85,130);ctx.font='20px Arial';ctx.fillText(labels[current.category],85,240);ctx.fillStyle='#303526';ctx.font='52px Georgia';let lines=[],line='';for(const word of current.text.split(' ')){const next=line?line+' '+word:word;if(ctx.measureText(next).width>900&&line){lines.push(line);line=word;}else line=next;}lines.push(line);lines.forEach((l,i)=>ctx.fillText(l,85,440+i*70));ctx.strokeStyle='#cbd2be';ctx.beginPath();ctx.moveTo(85,870);ctx.lineTo(995,870);ctx.stroke();ctx.fillStyle='#3f593d';ctx.font='25px Arial';ctx.fillText('Squeeze your own little pick-me-up.',85,925);ctx.font='22px Arial';ctx.fillText('iflifegivesyoulemons.com',85,980);canvas.toBlob(b=>b?resolve(b):reject(new Error('Image unavailable')),'image/png');});}
$('download').onclick=async()=>{try{const blob=await imageBlob();const href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download='a-little-lemon-'+current.id+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(href),30000);track('save_image');$('status').textContent='Your lemon card is ready to save.';}catch{$('status').textContent='Image could not be saved. Try sharing the link instead.';}};
if(/^https:\/\//.test(config.checkoutUrl||'')){const a=document.createElement('a');a.className='buy';a.href=config.checkoutUrl;a.textContent='Get the Little Zest Pack · €4.99';a.rel='noopener';a.onclick=()=>track('product_click');$('buywrap').replaceChildren(a);}
if(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(config.enquiryEmail||'')){$('enquiry').hidden=false;$('enquiry').href='mailto:'+config.enquiryEmail+'?subject=Domain%20acquisition%20enquiry';}
$('year').textContent=new Date().getFullYear();
if(/^https:\/\//.test(config.analyticsScriptUrl||'')&&config.analyticsDomain){const script=document.createElement('script');script.defer=true;script.src=config.analyticsScriptUrl;script.dataset.domain=config.analyticsDomain;document.head.appendChild(script);}
})();
